---
- hosts: localhost
  tasks:
    - stat:
        path: "{{ id_rsa_file }}"
      register: op

    - name: Generating ssh key pair
      command: ssh-keygen -t rsa -b 4096 -f "{{ id_rsa_file }}"
      when: op.stat.exists == false


    - debug:
        msg: "Key pair already exists. Using the same key."
      when: op.stat.exists

    - name: Copy public key to the nodes
      command: ssh-copy-id -i "{{ id_rsa_file }}" ansadmin@"{{ item }}" -f -o StrictHostKeyChecking=no
      with_items:
        - "{{ nodes }}"

  vars_files:
    - config.yml